### ISSUE TITLE
Help setting up dev 

### ISSUE THREAD

**Issue by AGMETEOR** [worldcoin/developer-portal#351]
After set up, I am having an issue with the login route, I see the following error in the logs
```log
error - ApolloError: fetch failed
    at new ApolloError (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/@apollo+client@3.7.11_graphql@16.6.0_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/errors/errors.cjs:31:28)
    at Object.error (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/@apollo+client@3.7.11_graphql@16.6.0_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/core/core.cjs:1343:90)
    at notifySubscription (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:240:7)
    at Object.error (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/@apollo+client@3.7.11_graphql@16.6.0_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/utilities/utilities.cjs:1088:69)
    at notifySubscription (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:240:7)
    at /Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/@apollo+client@3.7.11_graphql@16.6.0_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/utilities/utilities.cjs:1055:68
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/@apollo+client@3.7.11_graphql@16.6.0_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/utilities/utilities.cjs:1055:25)
    at Object.error (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/@apollo+client@3.7.11_graphql@16.6.0_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/utilities/utilities.cjs:1159:21)
    at notifySubscription (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:240:7)
    at notifySubscription (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/zen-observable@0.8.15/node_modules/zen-observable/lib/Observable.js:240:7)
    at handleError (/Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/@apollo+client@3.7.11_graphql@16.6.0_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/link/http/http.cjs:318:67)
    at /Users/allan/Desktop/COMMUNITY/developer-portal/web/node_modules/.pnpm/@apollo+client@3.7.11_graphql@16.6.0_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/link/http/http.cjs:619:48
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  graphQLErrors: [],
  protocolErrors: [],
  clientErrors: [],
  networkError: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11576:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: AggregateError
        at internalConnectMultiple (node:net:1114:18)
        at afterConnectMultiple (node:net:1667:5) {
      code: 'ECONNREFUSED',
      [errors]: [Array]
    }
  },
  extraInfo: undefined,
  page: '/login'
}
```

**Comment by AGMETEOR** [comment]
Yep looks like it's running
```log
CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                    PORTS                      NAMES
ef14ae2e51e8   hasura/graphql-engine:v2.28.0.cli-migrations-v3   "docker-entrypoint.s…"   48 minutes ago   Up 47 minutes (healthy)   0.0.0.0:8080->8080/tcp     developer-portal-hasura-1
```
